### ISSUE TITLE
Server Error: 403 - Forbidden: Access is denied - when trying to download mp4 files

### ISSUE THREAD

**Issue by VirtualGirl** [lamw/vmworld2016-session-urls#5]
Hello. I am trying to download select mp4 sessions, and all I am getting in any of the ones I try is the following error:

403 - Forbidden: Access is denied.
You do not have permission to view this directory or page using the credentials that you supplied.

Any help will be appreciated.

Thank you.

**Comment by Th3NightHawk** [comment]
Yep, guessing the session originally generated has expired...

**Comment by lamw** [comment]
I've just updated the download URLs again. The session tokens don't last too long, so have to constantly update it every few days. Grab them while you can as I'll be out on PTO tomorrow :)

**Comment by VirtualGirl** [comment]
Thank you, I was able to download most of the sessions I am interested it but I am still missing some but ran out of time, would you be able to download the URLs again please? And let me know? It seemed they only lasted one day.

Thanks again in advance.
